/**
 * Canvas export helpers — SVG snapshot of the React Flow canvas, plus a
 * markdown lab report bundling topology + CVEs + ATT&CK tags + provider
 * details. PNG is intentionally not in this module: rendering text-on-
 * canvas requires html-to-image or html2canvas, which we don't ship by
 * default. SVG round-trips cleanly through any vector tool the user
 * needs (Figma, Illustrator, Inkscape).
 */
import type { LabConfig } from "@labforge/schema";

/**
 * Grab the rendered React Flow `<svg>` element, clone it, freeze the
 * computed viewBox, and serialize. The clone is necessary because React
 * Flow may swap the live DOM out from under us between read and write.
 */
export function exportCanvasSvg(rootSelector = ".react-flow__viewport"): string | null {
  if (typeof document === "undefined") return null;
  const viewport = document.querySelector(rootSelector);
  if (!viewport) return null;
  // Find the outer ReactFlow container, which holds the `<svg>` overlay
  // we want.
  const rf = viewport.closest(".react-flow");
  if (!rf) return null;
  const svg = rf.querySelector("svg");
  if (!svg) return null;
  const clone = svg.cloneNode(true) as SVGSVGElement;
  // Inline a minimal CSS reset so the saved file renders standalone.
  const style = document.createElementNS("http://www.w3.org/2000/svg", "style");
  style.textContent = `
    .react-flow__edge-path { stroke: #475569; stroke-width: 1.5; fill: none; }
    .react-flow__edge-text { font: 11px ui-sans-serif, system-ui, sans-serif; fill: #475569; }
  `;
  clone.insertBefore(style, clone.firstChild);
  return new XMLSerializer().serializeToString(clone);
}

export function downloadString(content: string, filename: string, mime: string): void {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}

/**
 * Build a self-contained markdown report — the same content the user
 * gets in the generated zip's README, but driven by the live canvas
 * state. Useful for "share my lab plan" before generating the bundle.
 */
export function buildLabReport(topology: LabConfig): string {
  const lines: string[] = [];
  lines.push(`# ${topology.name}`);
  lines.push("");
  if (topology.description) {
    lines.push(topology.description);
    lines.push("");
  }
  lines.push(`- **Network**: ${topology.network_cidr}`);
  lines.push(`- **Provider**: ${topology.provider}`);
  lines.push(`- **Nodes**: ${topology.nodes.length}`);
  lines.push(`- **Edges**: ${topology.edges.length}`);
  lines.push(`- **Zones**: ${(topology.zones ?? []).length}`);
  lines.push("");

  lines.push("## Nodes");
  lines.push("");
  lines.push("| Hostname | Type | OS | IP | RAM | CPU | Roles | CVEs |");
  lines.push("|----------|------|----|----|----|----|-------|------|");
  for (const n of topology.nodes) {
    lines.push(
      `| \`${n.config.hostname}\` | ${n.type} | ${n.config.os} | \`${n.config.ip}\` | ` +
        `${n.config.memory_mb} MB | ${n.config.cpus} | ` +
        `${n.config.roles.join(", ") || "—"} | ${n.config.cves.join(", ") || "—"} |`,
    );
  }
  lines.push("");

  const tagged = topology.nodes.filter((n) => n.attack_tags && n.attack_tags.length > 0);
  if (tagged.length > 0) {
    lines.push("## MITRE ATT&CK coverage");
    lines.push("");
    for (const n of tagged) {
      lines.push(`### \`${n.config.hostname}\``);
      lines.push("");
      for (const tag of n.attack_tags ?? []) {
        const technique = tag.technique ? ` — ${tag.technique}` : "";
        const note = tag.note ? ` _(${tag.note})_` : "";
        lines.push(`- **${tag.tactic}**${technique}${note}`);
      }
      lines.push("");
    }
  }

  if (topology.edges.length > 0) {
    lines.push("## Edges");
    lines.push("");
    const nodeById = new Map(topology.nodes.map((n) => [n.id, n.config.hostname]));
    for (const e of topology.edges) {
      const src = nodeById.get(e.source) ?? e.source;
      const dst = nodeById.get(e.target) ?? e.target;
      const port = e.port ? `:${e.port}` : "";
      lines.push(`- \`${src}\` → \`${dst}\` (${e.protocol}${port})`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push(`_Generated by LabForge on ${new Date().toISOString()}_`);
  return lines.join("\n");
}
