"""Re-export the shared schema so backend code can import from one place."""

from labforge_schema import (
    CVEEntry,
    Credentials,
    LabConfig,
    NodeConfig,
    NodeType,
    OsType,
    Position,
    Protocol,
    Provider,
    Severity,
    TopologyEdge,
    TopologyNode,
    TopologySchema,
    ValidationIssue,
    ValidationResult,
    DEFAULT_OS_PER_NODE_TYPE,
    NODE_TYPE_LABELS,
    OS_LABELS,
)
from labforge_core.schemas.api import (
    ActivityEntry,
    ErrorResponse,
    GenerateRequest,
    HeartbeatPayload,
    LabCreateRequest,
    LabSummary,
    TemplateSummary,
    VmState,
)

__all__ = [
    "CVEEntry",
    "Credentials",
    "LabConfig",
    "NodeConfig",
    "NodeType",
    "OsType",
    "Position",
    "Protocol",
    "Provider",
    "Severity",
    "TopologyEdge",
    "TopologyNode",
    "TopologySchema",
    "ValidationIssue",
    "ValidationResult",
    "DEFAULT_OS_PER_NODE_TYPE",
    "NODE_TYPE_LABELS",
    "OS_LABELS",
    "ActivityEntry",
    "ErrorResponse",
    "GenerateRequest",
    "HeartbeatPayload",
    "LabCreateRequest",
    "LabSummary",
    "TemplateSummary",
    "VmState",
]
